#!/usr/bin/env sh
set -e

PUZZLE_GENERATOR_LIMIT="${PUZZLE_GENERATOR_LIMIT:-50}" \
PUZZLE_GENERATOR_MOVE_TIME_MS="${PUZZLE_GENERATOR_MOVE_TIME_MS:-150}" \
PUZZLE_GENERATOR_MULTIPV="${PUZZLE_GENERATOR_MULTIPV:-3}" \
PUZZLE_GENERATOR_STATUS="${PUZZLE_GENERATOR_STATUS:-draft}" \
docker compose -f docker-compose.yml run --rm puzzle-generator
