export const TOURNAMENT_MAX_PLAYERS = 50;
export const TOURNAMENT_MAX_ROUNDS = 50;
export const TOURNAMENT_NEXT_ROUND_DELAY_SECONDS = 15;
export const TOURNAMENT_MIN_ROUND_DELAY_SECONDS = 0;
export const TOURNAMENT_MAX_ROUND_DELAY_SECONDS = 3600;
export const TOURNAMENT_MIN_COFFEE_BREAK_MINUTES = 1;
export const TOURNAMENT_MAX_COFFEE_BREAK_MINUTES = 120;
